spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/harsha2nani/MS-Config
          default-label: Main
          search-paths:
            - Environments
server:
  port: 8085
